### ISSUE TITLE
No such file or directory: '/tmp/RetainedLoopValues.txt'

### ISSUE THREAD

**Issue by mflage** [steepleian/weewx-Weather34#4]
Hi!

the weather34 skin just brought the whole weather station down. Got the following:

```
Jun 14 21:28:41 raspberrypi weewx[7271]: w34rt: [Errno 2] No such file or directory: '/tmp/RetainedLoopValues.txt'
Jun 14 21:28:41 raspberrypi weewx[7271]: w34rt: w34rt: Exception while handling data: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
Jun 14 21:28:41 raspberrypi weewx[7271]: crt: **** Traceback (most recent call last):
Jun 14 21:28:41 raspberrypi weewx[7271]: crt: ****   File "/usr/share/weewx/user/weather34.py", line 545, in handle_data
Jun 14 21:28:41 raspberrypi weewx[7271]: crt: ****     data = self.calculate(event_data, dbm)
Jun 14 21:28:41 raspberrypi weewx[7271]: crt: ****   File "/usr/share/weewx/user/weather34.py", line 736, in calculate
Jun 14 21:28:41 raspberrypi weewx[7271]: crt: ****     data['sunshine_hours'] = calc_daylight_hours(alm)
Jun 14 21:28:41 raspberrypi weewx[7271]: crt: ****   File "/usr/share/weewx/user/weather34.py", line 267, in calc_daylight_hours
Jun 14 21:28:41 raspberrypi weewx[7271]: crt: ****     return (sunset - sunrise) / 3600.0
Jun 14 21:28:41 raspberrypi weewx[7271]: crt: **** TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
Jun 14 21:28:41 raspberrypi weewx[7271]: engine: Main loop exiting. Shutting engine down.
Jun 14 21:28:41 raspberrypi weewx[7271]: engine: Caught unrecoverable exception in engine:
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****  unsupported operand type(s) for -: 'NoneType' and 'NoneType'
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****  Traceback (most recent call last):
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****    File "/usr/share/weewx/weewx/engine.py", line 894, in main
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****      engine.run()
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****    File "/usr/share/weewx/weewx/engine.py", line 191, in run
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****      self.dispatchEvent(weewx.Event(weewx.NEW_LOOP_PACKET, packet=packet))
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****    File "/usr/share/weewx/weewx/engine.py", line 224, in dispatchEvent
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****      callback(event)
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****    File "/usr/share/weewx/user/weather34.py", line 537, in handle_new_loop
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****      self.handle_data(event.packet)
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****    File "/usr/share/weewx/user/weather34.py", line 545, in handle_data
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****      data = self.calculate(event_data, dbm)
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****    File "/usr/share/weewx/user/weather34.py", line 736, in calculate
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****      data['sunshine_hours'] = calc_daylight_hours(alm)
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****    File "/usr/share/weewx/user/weather34.py", line 267, in calc_daylight_hours
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****      return (sunset - sunrise) / 3600.0
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****  TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
Jun 14 21:28:41 raspberrypi weewx[7271]:     ****  Exiting.
```
Is this a known issue?

**Comment by mflage** [comment]
Ah! I just realized this must be due to the fact we have the midnight sun here, so the sun "never" sets.... :D So I guess you need to account for that.

**Comment by steepleian** [comment]
I think that may be a WeeWX problem as well. I discovered that when
installed WeeWX with the default settings of the North Pole.

**Comment by mflage** [comment]
I fixed it for me by just modifying the function calc_daylight_hours to:

```python
def calc_daylight_hours(alm):
    sunrise = alm.sunrise.raw
    sunset = alm.sunset.raw
    if alm.time_ts <= sunrise:
        return 0
    elif alm.time_ts < sunset:
        return (alm.time_ts - sunrise) / 3600.0
    # Norway says hi!
    if not sunset:
        return 24
    return (sunset - sunrise) / 3600.0
```
I attempted to create a PR for that, but it seems like the Norwegian branch is gone? And the same with the closed issue #20? Are you deleting closed issues?

**Comment by steepleian** [comment]
Hi Marius,
I consolidated a lot of stuff into the development branch. Just make a push
request there. Sorry for the confusion.
Thanks,
Ian

**Comment by balloonhotair** [comment]
The error message that is the title of this issue is expected if one is using caching for the first time.
