### ISSUE TITLE
Error when installing using preferred (first listed) method

### ISSUE THREAD

**Issue by m90att** [steepleian/weewx-Weather34#5]
Hi, 

I get this error when running the install (the first install method in INSTALLATION_GUIDE.md, which prevents installation from progressing:

```
pi@weatherpi:~/weewx-Weather34 $ sudo python w34_installer.py
!!! THIS INSTALL IS USING PYTHON VERSION 2.7.16 IS THIS CORRECT? (Yes/No) Yes

Install will continue with Python Version 2.7.16
1 -> macos.conf
2 -> setup_py.conf
3 -> packaged.conf
Enter the NUMBER of the installer config file 2
Installer Config file setup_py.conf was chosen.
Traceback (most recent call last):
  File "w34_installer.py", line 80, in __init__
    d.update(eval(re.sub(".*\"##.*\n",'', infile.read()).replace("\n", "").replace("\t", "")))
  File "<string>", line 2
    {
    ^
IndentationError: unexpected indent
unexpected indent (<string>, line 2)
```

**Comment by m90att** [comment]
Same error using the second method too

**Comment by m90att** [comment]
[weewx.zip](https://github.com/steepleian/weewx-Weather34/files/5454336/weewx.zip)
debug file

**Comment by m90att** [comment]
Can't recall how do do a syslog report into a file, so I've pasted it here...

```
Oct 28 19:01:13 weatherpi wee_import[18482] INFO weewx.engine: StdConvert target unit is 0x1
Oct 28 19:01:13 weatherpi wee_import[18482] INFO weewx.engine: Archive will use data binding wx_binding
Oct 28 19:01:13 weatherpi wee_import[18482] INFO weewx.engine: Record generation will be attempted in 'hardware'
Oct 28 19:01:13 weatherpi wee_import[18482] INFO weewx.engine: Using archive interval of 300 seconds (specified by hardware)
Oct 28 19:01:13 weatherpi wee_import[18482] INFO weewx.restx: StationRegistry: Registration not requested.
Oct 28 19:01:13 weatherpi wee_import[18482] INFO weewx.restx: Wunderground: Posting not enabled.
Oct 28 19:01:13 weatherpi wee_import[18482] INFO weewx.restx: PWSweather: Posting not enabled.
Oct 28 19:01:13 weatherpi wee_import[18482] INFO weewx.restx: CWOP: Posting not enabled.
Oct 28 19:01:13 weatherpi wee_import[18482] INFO weewx.restx: WOW: Posting not enabled.
Oct 28 19:01:13 weatherpi wee_import[18482] INFO weewx.restx: AWEKAS: Posting not enabled.
Oct 28 19:02:23 weatherpi wee_import[18482] INFO weewx.manager: Starting backfill of daily summaries
Oct 28 19:02:59 weatherpi wee_import[18482] INFO weewx.manager: Processed 8336 records to backfill 29 day summaries in 35.34 seconds
Oct 28 19:02:59 weatherpi wee_import[18482] INFO weecfg.database: Processed 29 days consisting of 8336 records. 29 days consisting of 8336 records were updated in 105.98 seconds.
Oct 28 19:02:59 weatherpi wee_import[18482] INFO weeimport.weeimport: Finished calculating missing derived observations
Oct 28 19:02:59 weatherpi wee_import[18482] INFO weeimport.weeimport: Finished import
Oct 28 19:02:59 weatherpi wee_import[18482] INFO weeimport.weeimport: 8336 records were processed and 8336 unique records imported in 405.08 seconds.
Oct 28 19:03:10 weatherpi systemd[1]: Starting LSB: weewx weather system...
Oct 28 19:03:11 weatherpi weewx[18532] INFO __main__: Initializing weewx version 4.2.0
Oct 28 19:03:11 weatherpi weewx[18532] INFO __main__: Using Python 2.7.16 (default, Oct 10 2019, 22:02:15) #012[GCC 8.3.0]
Oct 28 19:03:11 weatherpi weewx[18532] INFO __main__: Platform Linux-5.4.51-v7+-armv7l-with-debian-10.4
Oct 28 19:03:11 weatherpi weewx[18532] INFO __main__: Locale is 'en_GB.UTF-8'
Oct 28 19:03:11 weatherpi weewx[18532] INFO __main__: PID file is /var/run/weewx.pid
Oct 28 19:03:11 weatherpi weewx[18537] INFO __main__: Using configuration file /home/weewx/weewx.conf
Oct 28 19:03:11 weatherpi weewx[18537] INFO __main__: Debug is 0
Oct 28 19:03:11 weatherpi weewx[18522]: Starting weewx weather system: weewx.
Oct 28 19:03:11 weatherpi systemd[1]: Started LSB: weewx weather system.
Oct 28 19:03:11 weatherpi weewx[18537] INFO weewx.engine: Loading station type HP1000 (user.HP1000)
Oct 28 19:03:11 weatherpi weewx[18537] INFO root: HP100: HP1000 Starting
Oct 28 19:03:11 weatherpi weewx[18537] INFO root: HP100: Using user-defined broadcast mask - 192.168.86.54
Oct 28 19:03:11 weatherpi weewx[18537] INFO root: HP100: Address Mask = 192.168.86.54
Oct 28 19:03:11 weatherpi weewx[18537] INFO root: HP100: Retry count = 5.000000
Oct 28 19:03:11 weatherpi weewx[18537] INFO root: HP100: Socket timeout = 5.000000
Oct 28 19:03:11 weatherpi weewx[18537] INFO root: HP100: Loop delay = 15.000000
Oct 28 19:03:11 weatherpi weewx[18537] INFO root: HP100: Retry Wait = 5.000000
Oct 28 19:03:11 weatherpi weewx[18537] INFO root: HP100: Max Retry = 3.000000
Oct 28 19:03:11 weatherpi weewx[18537] INFO weewx.engine: StdConvert target unit is 0x1
Oct 28 19:03:11 weatherpi weewx[18537] INFO weewx.engine: Archive will use data binding wx_binding
Oct 28 19:03:11 weatherpi weewx[18537] INFO weewx.engine: Record generation will be attempted in 'hardware'
Oct 28 19:03:11 weatherpi weewx[18537] INFO weewx.engine: Using archive interval of 300 seconds (specified in weewx configuration)
Oct 28 19:03:11 weatherpi weewx[18537] INFO weewx.restx: StationRegistry: Registration not requested.
Oct 28 19:03:11 weatherpi weewx[18537] INFO weewx.restx: Wunderground: Posting not enabled.
Oct 28 19:03:11 weatherpi weewx[18537] INFO weewx.restx: PWSweather: Posting not enabled.
Oct 28 19:03:11 weatherpi weewx[18537] INFO weewx.restx: CWOP: Posting not enabled.
Oct 28 19:03:11 weatherpi weewx[18537] INFO weewx.restx: WOW: Posting not enabled.
Oct 28 19:03:11 weatherpi weewx[18537] INFO weewx.restx: AWEKAS: Posting not enabled.
Oct 28 19:03:11 weatherpi weewx[18537] INFO __main__: Starting up weewx version 4.2.0
Oct 28 19:03:11 weatherpi weewx[18537] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
Oct 28 19:03:11 weatherpi weewx[18537] INFO weewx.manager: Starting backfill of daily summaries
Oct 28 19:03:12 weatherpi weewx[18537] INFO root: HP100: Connected to address ('192.168.86.54', 50324)
Oct 28 19:03:13 weatherpi weewx[18537] INFO root: HP100: Established contact at 28/10/20 19:03:13
Oct 28 19:03:13 weatherpi weewx[18537] INFO root: HP100: Retrieving startup records
Oct 28 19:03:33 weatherpi weewx[18537] INFO weewx.manager: Added record 2020-10-28 18:52:09 GMT (1603911129) to database 'weewx.sdb'
Oct 28 19:03:33 weatherpi weewx[18537] INFO weewx.manager: Added record 2020-10-28 18:52:09 GMT (1603911129) to daily summary in 'weewx.sdb'
Oct 28 19:03:34 weatherpi weewx[18537] INFO weewx.manager: Added record 2020-10-28 18:57:09 GMT (1603911429) to database 'weewx.sdb'
Oct 28 19:03:34 weatherpi weewx[18537] INFO weewx.manager: Added record 2020-10-28 18:57:09 GMT (1603911429) to daily summary in 'weewx.sdb'
Oct 28 19:03:50 weatherpi weewx[18537] INFO weewx.engine: Starting main packet loop.
Oct 28 19:05:24 weatherpi weewx[18537] INFO weewx.manager: Added record 2020-10-28 19:05:00 GMT (1603911900) to database 'weewx.sdb'
Oct 28 19:05:24 weatherpi weewx[18537] INFO weewx.manager: Added record 2020-10-28 19:05:00 GMT (1603911900) to daily summary in 'weewx.sdb'
Oct 28 19:05:31 weatherpi weewx[18537] INFO weewx.cheetahgenerator: Generated 17 files for report SeasonsReport in 6.07 seconds
Oct 28 19:05:36 weatherpi weewx[18537] INFO weewx.imagegenerator: Generated 30 images for report SeasonsReport in 5.05 seconds
Oct 28 19:05:36 weatherpi weewx[18537] INFO weewx.reportengine: Copied 5 files to /var/www/html
Oct 28 19:09:00 weatherpi systemd[1]: Starting Clean php session files...
Oct 28 19:09:01 weatherpi systemd[1]: phpsessionclean.service: Succeeded.
Oct 28 19:09:01 weatherpi systemd[1]: Started Clean php session files.
Oct 28 19:09:01 weatherpi CRON[18653]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Oct 28 19:10:28 weatherpi weewx[18537] INFO weewx.manager: Added record 2020-10-28 19:10:00 GMT (1603912200) to database 'weewx.sdb'
Oct 28 19:10:28 weatherpi weewx[18537] INFO weewx.manager: Added record 2020-10-28 19:10:00 GMT (1603912200) to daily summary in 'weewx.sdb'
Oct 28 19:10:31 weatherpi weewx[18537] INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 1.90 seconds
Oct 28 19:10:32 weatherpi weewx[18537] INFO weewx.imagegenerator: Generated 15 images for report SeasonsReport in 1.07 seconds
Oct 28 19:10:32 weatherpi weewx[18537] INFO weewx.reportengine: Copied 0 files to /var/www/html
Oct 28 19:15:29 weatherpi weewx[18537] INFO weewx.manager: Added record 2020-10-28 19:15:00 GMT (1603912500) to database 'weewx.sdb'
Oct 28 19:15:30 weatherpi weewx[18537] INFO weewx.manager: Added record 2020-10-28 19:15:00 GMT (1603912500) to daily summary in 'weewx.sdb'
Oct 28 19:15:33 weatherpi weewx[18537] INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 2.14 seconds
Oct 28 19:15:34 weatherpi weewx[18537] INFO weewx.imagegenerator: Generated 15 images for report SeasonsReport in 1.10 seconds
Oct 28 19:15:34 weatherpi weewx[18537] INFO weewx.reportengine: Copied 0 files to /var/www/html
Oct 28 19:17:01 weatherpi CRON[18780]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 28 19:20:20 weatherpi weewx[18537] INFO weewx.manager: Added record 2020-10-28 19:20:00 GMT (1603912800) to database 'weewx.sdb'
Oct 28 19:20:20 weatherpi weewx[18537] INFO weewx.manager: Added record 2020-10-28 19:20:00 GMT (1603912800) to daily summary in 'weewx.sdb'
Oct 28 19:20:23 weatherpi weewx[18537] INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 1.95 seconds
Oct 28 19:20:24 weatherpi weewx[18537] INFO weewx.imagegenerator: Generated 15 images for report SeasonsReport in 1.09 seconds
Oct 28 19:20:24 weatherpi weewx[18537] INFO weewx.reportengine: Copied 0 files to /var/www/html

```

**Comment by balloonhotair** [comment]
Need to see your services.txt file. You should have created it using the pre install page. Please post it here.

**Comment by m90att** [comment]
[services.txt](https://github.com/steepleian/weewx-Weather34/files/5456836/services.txt)

**Comment by balloonhotair** [comment]
Looks like the file is created with extra spaces. Try this version.
[services.txt](https://github.com/steepleian/weewx-Weather34/files/5459374/services.txt)

**Comment by balloonhotair** [comment]
Once you get the file I will delete it from this post.

**Comment by m90att** [comment]
Thank you, that works.  I was getting timeouts trying to connect to my weatherstation that restarts of weewx didn't fix.  Needed a reboot of the raspberry pi to resolve.  Thanks for your help with this (again)

**Comment by m90att** [comment]
Ok, so it's working but something isn't right, I'm sure it's got something to do with the units or skin settings.  I can't seem to get into the settings from the menu either, it just doesn't let me in.  Has something changed in that respect?  is there a password I need to enter?  thanks

![image](https://user-images.githubusercontent.com/56609577/97618360-d3cd9380-1a16-11eb-97c7-bcecaae42841.png)

**Comment by m90att** [comment]
Ok, so something isn't quite right
![image](https://user-images.githubusercontent.com/56609577/97620363-62dbab00-1a19-11eb-82d6-8af6984be59f.png)
The default report is ok so it's something to do with W34.  I've double checked the settings and they seem to be ok.  when clicking into the graphs, eg. temperature it is correct so it 's the main page that the issues are limited to I think

**Comment by balloonhotair** [comment]
Yes the location of the realtime.txt file has moved to a directory 
called serverdata.

So first check that you have the serverdata directory in the weather34 
directory.

If you do then go to your weewx.conf and search for w34realtime.txt file 
and make sure the path has serverdata directory in front of the file.

Thanks

**Comment by balloonhotair** [comment]
You will also need to restart weewx if you change the weewx.conf file

**Comment by m90att** [comment]
Thanks.  Yes the folder is there and the entry in weewx.conf is:

```
[Weather34RealTime]
    weewx_port = 25252
    cache_enable = True
    unit_system = METRICWX
    weewx_file_transfer = ""
    webserver_address = ""
    cache_stale_time = 900
    weewxserver_address = ""
    exclude_fields = rain
    cache_directory = /tmp
    filename = /var/www/html/weewx/weather34/serverdata/w34realtime.txt
```
but when I look in that directory there is no w34realtime.txt, only:

```
-rw-r--r--  1 root     root     4714 Oct 29 21:25 archivedata.php
-rwxr-xr-x  1 www-data www-data    1 Oct 28 16:59 placeholder.txt

```

**Comment by balloonhotair** [comment]
Well that is usually not possible since weather34.py writes into that directory and there should be a file. So does the filename entry in the weewx.conf exists (except for the actual file) and the machine that is running weewx has access to that directory? Are there any startup errors when weewx starts? Need to look in syslog.  Is there a w34realtime.txt file in the parent directory (expect an old one) and has a current date time?

**Comment by m90att** [comment]
The entry in weewx.conf exists.  The machine running weewx is a raspberry pi and the directory is on the pi.  

Startup log:

```
Oct 29 18:58:09 weatherpi systemd[1]: Starting LSB: weewx weather system...
Oct 29 18:58:09 weatherpi weewx[689] INFO __main__: Initializing weewx version 4.2.0
Oct 29 18:58:09 weatherpi weewx[689] INFO __main__: Using Python 2.7.16 (default, Oct 10 2019, 22:02:15) #012[GCC 8.3.0]
Oct 29 18:58:09 weatherpi weewx[689] INFO __main__: Platform Linux-5.4.51-v7+-armv7l-with-debian-10.4
Oct 29 18:58:09 weatherpi weewx[689] INFO __main__: Locale is 'en_GB.UTF-8'
Oct 29 18:58:09 weatherpi weewx[689] INFO __main__: PID file is /var/run/weewx.pid
Oct 29 18:58:09 weatherpi weewx[679]: Starting weewx weather system: weewx.
Oct 29 18:58:09 weatherpi systemd[1]: Started LSB: weewx weather system.
Oct 29 18:58:09 weatherpi weewx[694] INFO __main__: Using configuration file /home/weewx/weewx.conf
Oct 29 18:58:09 weatherpi weewx[694] INFO __main__: Debug is 0
Oct 29 18:58:09 weatherpi weewx[694] INFO weewx.engine: Loading station type HP1000 (user.HP1000)
Oct 29 18:58:09 weatherpi weewx[694] INFO root: HP100: HP1000 Starting
Oct 29 18:58:09 weatherpi weewx[694] INFO root: HP100: Using user-defined broadcast mask - 192.168.86.35
Oct 29 18:58:09 weatherpi weewx[694] INFO root: HP100: Address Mask = 192.168.86.35
Oct 29 18:58:09 weatherpi weewx[694] INFO root: HP100: Retry count = 5.000000
Oct 29 18:58:09 weatherpi weewx[694] INFO root: HP100: Socket timeout = 5.000000
Oct 29 18:58:09 weatherpi weewx[694] INFO root: HP100: Loop delay = 15.000000
Oct 29 18:58:09 weatherpi weewx[694] INFO root: HP100: Retry Wait = 5.000000
Oct 29 18:58:09 weatherpi weewx[694] INFO root: HP100: Max Retry = 3.000000
Oct 29 18:58:09 weatherpi weewx[694] INFO weewx.engine: StdConvert target unit is 0x1
Oct 29 18:58:09 weatherpi weewx[694] INFO weewx.engine: Archive will use data binding wx_binding
Oct 29 18:58:09 weatherpi weewx[694] INFO weewx.engine: Record generation will be attempted in 'hardware'
Oct 29 18:58:09 weatherpi weewx[694] INFO weewx.engine: Using archive interval of 300 seconds (specified in weewx configuration)
Oct 29 18:58:09 weatherpi weewx[694] INFO weewx.restx: StationRegistry: Registration not requested.
Oct 29 18:58:09 weatherpi weewx[694] INFO weewx.restx: Wunderground: Posting not enabled.
Oct 29 18:58:09 weatherpi weewx[694] INFO weewx.restx: PWSweather: Posting not enabled.
Oct 29 18:58:09 weatherpi weewx[694] INFO weewx.restx: CWOP: Posting not enabled.
Oct 29 18:58:09 weatherpi weewx[694] INFO weewx.restx: WOW: Posting not enabled.
Oct 29 18:58:09 weatherpi weewx[694] INFO weewx.restx: AWEKAS: Posting not enabled.
Oct 29 18:58:09 weatherpi weewx[694] INFO __main__: Starting up weewx version 4.2.0
Oct 29 18:58:09 weatherpi weewx[694] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
Oct 29 18:58:09 weatherpi weewx[694] INFO weewx.manager: Starting backfill of daily summaries
Oct 29 18:58:34 weatherpi weewx[694] INFO root: HP100: Timed out too many times
Oct 29 18:58:35 weatherpi weewx[694] INFO root: HP100: Connected to address ('192.168.86.35', 50022)
Oct 29 18:58:36 weatherpi weewx[694] INFO root: HP100: Established contact at 29/10/20 18:58:36
Oct 29 18:58:36 weatherpi weewx[694] INFO root: HP100: Retrieving startup records
Oct 29 18:58:50 weatherpi weewx[694] INFO weewx.engine: Starting main packet loop.
Oct 29 19:00:24 weatherpi weewx[694] INFO weewx.manager: Added record 2020-10-29 19:00:00 GMT (1603998000) to database 'weewx.sdb'
Oct 29 19:00:24 weatherpi weewx[694] INFO weewx.manager: Added record 2020-10-29 19:00:00 GMT (1603998000) to daily summary in 'weewx.sdb'

```

Nothing I can spot that is wrong.
There is not w34realtime.txt file anywhere

**Comment by balloonhotair** [comment]
need to make real sure that weewx is using the weex.conf file that has the serverdata directory in it.  Make sure that weewx.conf entry  has weather34Realtime 
process_services = weewx.engine.StdConvert, weewx.engine.StdCalibrate, weewx.engine.StdQC, weewx.wxservices.StdWXCalculate,user.weather34.Weather34RealTime
Also set weewx debug to 1 and restart weewx and post the log from the startup point.

**Comment by m90att** [comment]
definitely has the w34realtime.txt entry
also has this:
`process_services = weewx.engine.StdConvert, weewx.engine.StdCalibrate, weewx.engine.StdQC, weewx.wxservices.StdWXCalculate`
but I can't find user.weather34.Weather34RealTime

syslog with debug = 1:
```
Oct 29 22:14:52 weatherpi systemd[1]: Starting LSB: weewx weather system...
Oct 29 22:14:53 weatherpi weewx[1786] INFO __main__: Initializing weewx version 4.2.0
Oct 29 22:14:53 weatherpi weewx[1786] INFO __main__: Using Python 2.7.16 (default, Oct 10 2019, 22:02:15) #012[GCC 8.3.0]
Oct 29 22:14:53 weatherpi weewx[1786] INFO __main__: Platform Linux-5.4.51-v7+-armv7l-with-debian-10.4
Oct 29 22:14:53 weatherpi weewx[1786] INFO __main__: Locale is 'en_GB.UTF-8'
Oct 29 22:14:53 weatherpi weewx[1786] INFO __main__: PID file is /var/run/weewx.pid
Oct 29 22:14:53 weatherpi weewx[1776]: Starting weewx weather system: weewx.
Oct 29 22:14:53 weatherpi systemd[1]: Started LSB: weewx weather system.
Oct 29 22:14:53 weatherpi weewx[1791] INFO __main__: Using configuration file /home/weewx/weewx.conf
Oct 29 22:14:53 weatherpi weewx[1791] INFO __main__: Debug is 1
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG __main__: Initializing engine
Oct 29 22:14:53 weatherpi weewx[1791] INFO weewx.engine: Loading station type HP1000 (user.HP1000)
Oct 29 22:14:53 weatherpi weewx[1791] INFO root: HP100: HP1000 Starting
Oct 29 22:14:53 weatherpi weewx[1791] INFO root: HP100: Using user-defined broadcast mask - 192.168.86.35
Oct 29 22:14:53 weatherpi weewx[1791] INFO root: HP100: Address Mask = 192.168.86.35
Oct 29 22:14:53 weatherpi weewx[1791] INFO root: HP100: Retry count = 5.000000
Oct 29 22:14:53 weatherpi weewx[1791] INFO root: HP100: Socket timeout = 5.000000
Oct 29 22:14:53 weatherpi weewx[1791] INFO root: HP100: Loop delay = 15.000000
Oct 29 22:14:53 weatherpi weewx[1791] INFO root: HP100: Retry Wait = 5.000000
Oct 29 22:14:53 weatherpi weewx[1791] INFO root: HP100: Max Retry = 3.000000
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.engine.StdTimeSynch
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.engine.StdTimeSynch
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.engine.StdConvert
Oct 29 22:14:53 weatherpi weewx[1791] INFO weewx.engine: StdConvert target unit is 0x1
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.engine.StdConvert
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.engine.StdCalibrate
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.engine.StdCalibrate
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.engine.StdQC
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.engine.StdQC
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.wxservices.StdWXCalculate
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.manager: Daily summary version is 2
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.wxservices.StdWXCalculate
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.wxxtypes.StdWXXTypes
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.wxxtypes.StdWXXTypes
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.wxxtypes.StdPressureCooker
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.wxxtypes.StdPressureCooker
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.wxxtypes.StdRainRater
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.wxxtypes.StdRainRater
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.engine.StdArchive
Oct 29 22:14:53 weatherpi weewx[1791] INFO weewx.engine: Archive will use data binding wx_binding
Oct 29 22:14:53 weatherpi weewx[1791] INFO weewx.engine: Record generation will be attempted in 'hardware'
Oct 29 22:14:53 weatherpi weewx[1791] INFO weewx.engine: Using archive interval of 300 seconds (specified in weewx configuration)
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Use LOOP data in hi/low calculations: 1
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.engine.StdArchive
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.restx.StdStationRegistry
Oct 29 22:14:53 weatherpi weewx[1791] INFO weewx.restx: StationRegistry: Registration not requested.
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.restx.StdStationRegistry
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.restx.StdWunderground
Oct 29 22:14:53 weatherpi weewx[1791] INFO weewx.restx: Wunderground: Posting not enabled.
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.restx.StdWunderground
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.restx.StdPWSweather
Oct 29 22:14:53 weatherpi weewx[1791] INFO weewx.restx: PWSweather: Posting not enabled.
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.restx.StdPWSweather
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.restx.StdCWOP
Oct 29 22:14:53 weatherpi weewx[1791] INFO weewx.restx: CWOP: Posting not enabled.
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.restx.StdCWOP
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.restx.StdWOW
Oct 29 22:14:53 weatherpi weewx[1791] INFO weewx.restx: WOW: Posting not enabled.
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.restx.StdWOW
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.restx.StdAWEKAS
Oct 29 22:14:53 weatherpi weewx[1791] INFO weewx.restx: AWEKAS: Posting not enabled.
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.restx.StdAWEKAS
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.engine.StdPrint
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.engine.StdPrint
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Loading service weewx.engine.StdReport
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Finished loading service weewx.engine.StdReport
Oct 29 22:14:53 weatherpi weewx[1791] INFO __main__: Starting up weewx version 4.2.0
Oct 29 22:14:53 weatherpi weewx[1791] DEBUG weewx.engine: Station does not support reading the time
Oct 29 22:14:53 weatherpi weewx[1791] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
Oct 29 22:14:53 weatherpi weewx[1791] INFO weewx.manager: Starting backfill of daily summaries
Oct 29 22:15:11 weatherpi nmbd[540]: [2020/10/29 22:15:11.509899,  0] ../source3/nmbd/nmbd_namequery.c:109(query_name_response)
Oct 29 22:15:11 weatherpi nmbd[540]:   query_name_response: Multiple (2) responses received for a query on subnet 192.168.86.40 for name WORKGROUP<1d>.
Oct 29 22:15:11 weatherpi nmbd[540]:   This response was from IP 192.168.86.59, reporting an IP address of 192.168.86.59.
Oct 29 22:15:18 weatherpi weewx[1791] INFO root: HP100: Timed out too many times
Oct 29 22:15:19 weatherpi weewx[1791] INFO root: HP100: Connected to address ('192.168.86.35', 50936)
Oct 29 22:15:20 weatherpi weewx[1791] INFO root: HP100: Established contact at 29/10/20 22:15:20
Oct 29 22:15:20 weatherpi weewx[1791] INFO root: HP100: Retrieving startup records
Oct 29 22:15:35 weatherpi weewx[1791] INFO weewx.engine: Starting main packet loop.
Oct 29 22:17:01 weatherpi CRON[1825]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

```

**Comment by balloonhotair** [comment]
You need to add the service for this work.

**Comment by m90att** [comment]
ok. thanks. is this something I missed on installation - how do I add the service?

**Comment by balloonhotair** [comment]
In your weewx.conf services section add the weather34 service to the proccess_services config entry. Here is mind yours will be different but you want to have user.weather34.Weather34RealTime near or at the end of the list.
  process_services = weewx.engine.StdConvert, weewx.engine.StdCalibrate, weewx.engine.StdQC, weewx.wxservices.StdWXCalculate, user.sc.SensorClient, user.weather34.Weather34RealTime, user.plp.PostLoopPacket

**Comment by m90att** [comment]
That's fixed it!  Thank you for your ongoing help and patience.  On a related note, do you know why the service wasn't written to the weewx.conf file?  There is not explicit instruction to do so, so that implies that it is done as part of the installer script?

**Comment by balloonhotair** [comment]
Here is my best guess. The installer has a flag in the config to decide if it is going to overwrite existing config entries. In the past it was set to true so that if the installer found an entry is would replace it. This way the installer always updated everything. In this release it was turned to false by request of Ian who was concerned that an install on an existing system would overwrite user's changes, which is a valid concern. But now since process_services is an existing config entry it was skipped, looks like the check needs to be more finer and only skip if what is being added already exits then skip it else append it.

**Comment by m90att** [comment]
That makes perfect sense, thank you.  Thank you too for all your hard work in making it a great template all round. From: balloonhotairSent: 30 October 2020 16:01To: steepleian/weewx-Weather34Cc: m90att; AuthorSubject: Re: [steepleian/weewx-Weather34] Error when installing using preferred (first listed) method (#5) Here is my best guess. The installer has a flag in the config to decide if it is going to overwrite existing config entries. In the past it was set to true so that if the installer found an entry is would replace it. This way the installer always updated everything. In this release it was turned to false by request of Ian who was concerned that an install on an existing system would overwrite user's changes, which is a valid concern. But now since process_services is an existing config entry it was skipped, looks like the check needs to be more finer and only skip if what is being added already exits then skip it else append it.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by balloonhotair** [comment]
Installer is now going to update an entry if the entry is there but the data is not when override is false.
